services:
  # FastAPI Backend Service
  - type: web
    name: betflow-api
    env: python
    plan: starter
    buildCommand: |
      pip install -r api/requirements.txt
      pip install -r engine/requirements.txt
      alembic -c db/alembic.ini upgrade head
      python api/scripts/seed_demo_data.py
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: betflow-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: betflow-redis
          property: connectionString
      - key: API_RATE_LIMIT
        value: "100"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: "admin@betflow-engine.com"
      - key: PROVIDERS_ODDS_API_KEY
        value: "YOUR_ODDS_API_KEY_HERE"
      - key: PROVIDERS_SPORTS_MONKS_KEY
        value: "YOUR_SPORTS_MONKS_KEY_HERE"
      - key: N8N_WEBHOOK_URL
        value: "https://betflow-worker.onrender.com/webhook"
      - key: ENVIRONMENT
        value: "production"
      - key: LOG_LEVEL
        value: "INFO"

  # Background Worker Service
  - type: worker
    name: betflow-worker
    env: python
    plan: starter
    buildCommand: |
      pip install -r api/requirements.txt
      pip install -r engine/requirements.txt
    startCommand: python -m n8n start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: betflow-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: betflow-redis
          property: connectionString
      - key: N8N_WEBHOOK_URL
        value: "https://betflow-worker.onrender.com/webhook"
      - key: PROVIDERS_ODDS_API_KEY
        value: "YOUR_ODDS_API_KEY_HERE"
      - key: PROVIDERS_SPORTS_MONKS_KEY
        value: "YOUR_SPORTS_MONKS_KEY_HERE"
      - key: ENVIRONMENT
        value: "production"
      - key: LOG_LEVEL
        value: "INFO"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true

  # Next.js Frontend Service
  - type: web
    name: betflow-web
    env: node
    plan: starter
    buildCommand: |
      cd web
      npm install
      npm run build
    startCommand: cd web && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: "https://betflow-api.onrender.com"
      - key: NODE_ENV
        value: "production"

databases:
  - name: betflow-postgres
    plan: starter
    databaseName: betflow
    user: betflow_user

  - name: betflow-redis
    type: redis
    plan: starter
