global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'betflow-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'betflow-web'
    static_configs:
      - targets: ['web:3000']
    scrape_interval: 30s

  - job_name: 'betflow-engine'
    static_configs:
      - targets: ['engine:8000']
    scrape_interval: 30s

  - job_name: 'betflow-n8n'
    static_configs:
      - targets: ['n8n:5678']
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
